namespace Bankreader.Application.Models
{
    public enum Category
    {
        Unknown,
        Groceries,
        MusicStreaming,
        Health,
        HealthInsurance,
        TravelInsurance,
        FuneralInsurance,
        HouseInsurance,
        HomeImprovement,
        Bank,
        PublicTransit,
        Housing,
        Tax,
        Creditcard,
        Clothing,
        Cash,
        Amusement,
        MobilePhone,
        Water,
        Electricity,
        Salary,
        Savings,
        Car,
        Restaurant,
        Purchase,
        PaymentRequest,
        Gym,
        Person
    }
}
